### ISSUE TITLE
Error 404 when trying to run the example 'wasm-shell'

### ISSUE THREAD

**Issue by alocquet** [wasmerio/wasmer-js#105]
When I follow the quickstart, I have a 404 error.

The steps I have followed :
* clone the repo
* npm install
* npm run dev
* --> Error 404

The problem is that 'npm run dev' launches the 'npx serve dist/' command and the 'dist' directory is empty.
I succeeded to run the example only after a 'npm run build' which generates js... in dist directory.

I don't know where is the problem (if we need to update scripts or update documentation) but I can help if you want :)

**Comment by torch2424** [comment]
Hello! @alocquet Thank you very much for opening the issue! 😄 

Yes, feel free to open a PR to solve the issue if you think you have a good solution 😄 I think it may be we need to document that you should build before trying to run the development server? 🤔 

In the meantime, I'll try and investigate this as well 👍 And feel free to reach out with more suggestions if you want to contribute anything!

**Comment by alocquet** [comment]
Perhaps we could improve scripts to build and watch sources when we serve. But you use some libraries (lerna, rollup, chokidar) I'm not used to and I won't have time to understand this quickly.

I think that improve the documentation should be a good first step for wasmer beginners like me :) I'll make a PR.

**Comment by torch2424** [comment]
@alocquet 

> Perhaps we could improve scripts to build and watch sources when we serve. But you use some libraries (lerna, rollup, chokidar) I'm not used to and I won't have time to understand this quickly.

Ah yes! So originally it did do that (Build before watching), but the build times on this project are a little long ~30s. So we made it so that not every `npm run dev` builds on the command. That being said, it should definitely do this, and will probably re-implement it once we get our build times faster. Thank you! 😄 

> I think that improve the documentation should be a good first step for wasmer beginners like me :) I'll make a PR.

Awesome! I approved and merged the PR! Thank you very much 😄 Stoked to know more people who are new won't run into the same hurdles 👍
