### ISSUE TITLE
On deploy, Also update the crate version

### ISSUE THREAD

**Issue by torch2424** [wasmerio/wasmer-js#117]
Currently, the rust crate is noot being updated with each deploy with lerna. Would also be nice to have some post deploy script to sync the cargo.toml with the package.json 😄

**Comment by Michael-F-Bryan** [comment]
I don't believe this is relevant now that we've rewritten the package as `@wasmer/sdk`. 

The *Release Please* job will automatically bump the version number in `package.json` when a release is made. We're deliberately leaving the Rust crate at version `0.0.0` and setting `publish = false` because it isn't the entire package - we do some bundling and have an additional `lib.ts` file which sets things up and re-exports the WebAssembly code.
