### ISSUE TITLE
Can't set environment variables in terminal

### ISSUE THREAD

**Issue by FranklinWaller** [wasmerio/wasmer-js#144]
Currently, there is no way of setting the environment variables in the terminal. Which causes you to not be able to run commands such as `pwd`.  It would be nice to be able to set environment variables before a command. Maybe by returning inside the fetchCommand? Something like:

```JavaScript
const wasmTerminal = new WasmTerminal({
    fetchCommand: (commandName) => {
        if (commandName === 'cd') {
            const callbackCommand = async (args) => {

                return {
                    bin: '' // Either the normal WASM binary or a string to output
                    env: [
                        ['$PWD', args[0]]
                    ]
                }
            }

            return callbackCommand
        }
    },
    wasmFs,
});
```

In the documentation there is an option for `fetchCommandFromWAPM` but it's only for that function available. (Also the envEntries are not being used https://github.com/wasmerio/wasmer-js/blob/master/packages/wasm-terminal/lib/functions/fetch-command-wapm.ts#L73)

**Comment by torch2424** [comment]
Hello @FranklinWaller !

Thank you for the issue!

I'm glad you brought this up. We made it so you can pass Enviornment variables to [`@wasmer/wasi`](https://github.com/wasmerio/wasmer-js/tree/master/packages/wasi#quick-start), but we hadn't considered it for the shell, because we thought of it is an all-in-one.

Perhaps it would be good to add a new "hook", such as "fetchEnvironmentVariables", that returns an object of the current environment variables to be spread across what we are currently doing? cc @syrusakbary 

And considering commands like `pwd`, a proper file system strategy has been something we've been working towards, with issues like #91 and #95 , this will definitely be something we should handle as well!

Thank you again, glad you brought this up, we'll keep this open as a feature request 😄

**Comment by torch2424** [comment]
@syrusakbary So I have been thinking about how to implement this. Looking at: 

https://github.com/wasmerio/wasmer-js/blob/master/packages/wasm-terminal/src/command-runner/command-runner.ts#L482

I think it makes sense if we do what @FranklinWaller suggests. And provide a new return type for fetchCommand:

```typescript
export interface FetchCommandResponse {
  module?: Uint8Array
  callback?: Function
  env?: string[]
}
```

Which allows us to keep our current return type, but also allows returning custom environment variables.

What do you think @syrusakbary ? 😄 👍

**Comment by Michael-F-Bryan** [comment]
With the new `@wasmer/sdk` package, you can do this using the `env` argument. For example,

```ts
const instance = await pkg.entrypoint.run({
    env: { RUST_LOG: "debug" },
    ...
});
```
