### ISSUE TITLE
Does not work with rollup

### ISSUE THREAD

**Issue by TJKoury** [wasmerio/wasmer-js#154]
My experience as been the following:

Using rollup on ./lib/index.cjs.js (using [rollup-plugin-commonjs](https://github.com/rollup/rollup-plugin-commonjs)) or on ./lib/index.esm.js (adding "type":"module" to the package.json) results in a bundle that cannot detect running in the Node environment.

Errors are thrown concerning browser APIs such as `ReferenceError: performance is not defined`, and even if those are shimmed the crypto implementation does not initialize correctly to use Node's `crypto` module.

I figured I would write it up in case I'm missing something obvious, before I start working on a pull request.

**Comment by torch2424** [comment]
Hello! Thanks for filing the issue! 😄 

So if you don't mind, can you answer a few questions?

1. What package are you trying to use? Packages like the `wasm-terminal` only support the browser because they use the DOM.
2. What are you trying to build using wasmer-js? Just run a simple one off WASI module?
3. Is the source code of what you are trying to do publicly available? If not, can you give us a quick example?

Thank you! 😄

**Comment by TJKoury** [comment]
@torch2424 Sorry, I should have specified, it’s the    ‘wasi’ package.  I’ll post the code shortly.

**Comment by torch2424** [comment]
@TJKoury No worries at all! 😄 

And feel free to mention me once the code is posted up. Also, if you can posted your rollup config as well 😄 

We recently added end to end tests (or whatever may be the right word for them), where we re-bundle the output of the packages with rollup: https://github.com/wasmerio/wasmer-js/blob/master/e2e-tests/test/wasi.js So there may be a case that we are missing 😄

**Comment by syrusakbary** [comment]
We are working on a fix. In order to know if what we have in mind will fix it, can you try the following and comment here if it worked?

```js
import { WASI } from '@wasmer/wasi/lib';

console.log(WASI); // prints "undefined"
```

> Note: We are importing `@wasmer/wasi/lib` instead of `@wasmer/wasi`

Thanks!

**Comment by torch2424** [comment]
@syrusakbary As discussed offline, this was an issue that is now solved by #156 , I think @TJKoury is experiencing a different issue

**Comment by TJKoury** [comment]
@syrusakbary I get the error:

`Cannot find module ./node_modules/@wasmer/wasi/lib`

**Comment by torch2424** [comment]
@TJKoury Ah yeah, so that issue was fixed, but I don't think it's related to your issue. 

But it is odd that you get: `Cannot find module ./node_modules/@wasmer/wasi/lib`. What about `./node_modules/@wasmer/wasi/lib/index.js`? **NOTE:** I'm just bikeshedding here, as this may mean you don't have the wasi package installed haha!

Either way, whenever you have an available source code, or an example that reproduces your issue, please let us know! 😄

**Comment by TJKoury** [comment]
@torch2424 I have it installed, but node isn't going to resolve a .js file when running with --experimental-modules and no "type":"module" in the nearest package.json.  I should have made that clear.

I'll post next when the code is up.

**Comment by TJKoury** [comment]
@torch2424 See [here](https://github.com/DigitalArsenal/openssl.js).

Relevant sections in [rollup.config](https://github.com/DigitalArsenal/openssl.js/blob/master/scripts/rollup.config.js) having to swap out imports based on browser / node.

**Comment by corwin-of-amber** [comment]
I had a similar experience and I resolved it locally by adding `@wasmer/*` to `external` on my cjs target, something like
```
{
    input: "src/kernel/index.ts",
    output: [{file: "dist/kernel.cjs.js", format: "cjs"}],
    external: ['@wasmer/wasi', '@wasmer/wasmfs']
}
```

It means that wasmer does not end up in your bundle though. It will be loaded via `require`.

**Comment by TJKoury** [comment]
@corwin-of-amber True, but the goal is to not have it external, especially because the browser will not use Node’s require algorithm to find it server side.

**Comment by corwin-of-amber** [comment]
Completely agree. I had to make separate browser (iife) and Node (cjs) bundles.

**Comment by torch2424** [comment]
@TJKoury My apologies! Was at Chrome Dev Summit, and hadn't been checking on github issues since most of my time was spent talking to other Wasm people!

Thanks for sharing your solution @corwin-of-amber , and I do agree this should be easier to use when trying to do multiple platforms.

Okay, so the reason why you have to do this weird switching for the browser and node, is because, the browser (esm bundle), and the node (cjs bundle) expect different globals and bindings used by the wasi package. Which is why bundling the esm version vs. bundling the commonjs version can have different experiences.

So if your goal is to also make a llibrary that has different bindings for both node and browser, I'd follow a pattern like this:

Losely similar to [wasm-transformer](https://github.com/wasmerio/wasmer-js/tree/master/packages/wasm-transformer/src), create two different entry points into your library: `node.js` and `browser.js`. And then create an abstracted `lib.js`, that receives the library object.

In your node version, require the commonjs bundle, and then pass the object to your required library.

In the browser version, import the esm bundle, and pass the bundle object to your imported library.

In rollup, use the browser entry point for your esm and iife bundles. And use the node entry point for your commonjs bundle

Let me know if that works for you. Or, I can try and make a PR for you. And I'm totally open to ideas on how to improve this, but due to the platform differences, I think that is going to be our best bet :(

**Comment by TJKoury** [comment]
@torch2424 Thanks for the reply!  You can see my solution (which is basically your suggested solution) here:  [OpenSSL.js](https://github.com/DigitalArsenal/openssl.js).

**Comment by torch2424** [comment]
@TJKoury Oh nice! Glad you got it figured out! 😄 

So is this issue still a problem? Or is there an action item here? Perhaps we should document this better? 😄 

Also, it is alright if we share OpenSSL.js ? Would be awesome to highlight the project! 👍

**Comment by TJKoury** [comment]
@torch2424 Yes, please do share it!  We are looking to collaborate on it with the community.

The issue is the browser not being detected properly, but I haven’t had time to dig though the code (I think it’s an order of operation bug).

**Comment by torch2424** [comment]
@TJKoury 

> Yes, please do share it! We are looking to collaborate on it with the community.

Awesome! Tweeted by [myself](https://twitter.com/torch2424/status/1195460301954568192), and retweeted by the Wasmer Twitter 😄 

> The issue is the browser not being detected properly, but I haven’t had time to dig though the code (I think it’s an order of operation bug).

Ah, thanks for clarifying. And this is on our end correct? Like our bundle output isn't being handled correctly still by rollup outputting for the browser? If so, I'll go ahead and try and do a rollup from scratch as well 👍 

Thanks! 😄

**Comment by happybeing** [comment]
I have what looks like a similar issue using rollup from the standard Svelte template.

All I do is add this line to `src/App.svelte`:
```import browserBindings from '@wasmer/wasi/lib/bindings/browser'```

Loading the app immediately causes the following error during the application `init()` in `src/main.js`
```
Uncaught ReferenceError: buffer$1 is not defined
    at main.js:8
```

Steps to reproduce:
```
npx degit sveltejs/template simple-svelte-wasmer-example
cd simple-svelte-wasmer-example
yarn && yarn dev
# works ok

yarn add @wasmer/wasi
# Add to App.svelte: import browserBindings from '@wasmer/wasi/lib/bindings/browser'
yarn dev
ERROR: main.js:8 Uncaught ReferenceError: buffer$1 is not defined
```

I've looked through the topic and realise there may be a way around this, but I don't understand yet how to apply that to my use case. I could try webpack but not sure if that would help.

FYI I'm hoping to use WASI in https://github.com/happybeing/p2p-git-portal-poc as a way to replace go-lang with Rust (and maybe wasm-git) to provide github functionality in the browser (no server-side).

**Comment by Michael-F-Bryan** [comment]
This should work with the new `@wasmer/sdk` package.
