### ISSUE TITLE
Information sparcity

### ISSUE THREAD

**Issue by mundusnine** [wasmerio/wasmer-js#173]
So this project really needs a wiki. I could share the info I have gathered as of now and project maintainers could share when they have time. 

The info that I found in this pr is a good example:

Actually, both WASI and Emscripten will use the same filesystem.
What you think on renaming it to `WasmerFileSystem` ?

_Originally posted by @syrusakbary in https://github.com/wasmerio/wasmer-js/pull/5_

Basicaly, it's great to know we can have interactions between wasm generated from emcc and from wasienv.

**Comment by torch2424** [comment]
Hello!

Thank you for bringing this up! 

We recently launched an official [documentation resource across the wasmer js stack](https://docs.wasmer.io/wasmer-js/wasmer-js). 

And related to that specific comment, We haven't really highlighted that feature yet, as it's not quite working yet if I am not mistaken. Currently, only the WASI ABI works, and the Emscripten ABI would be coming later (if that is what you are reffering to) 😄 Otherwise, can you expand on what you mean?

Thank you! 😄

**Comment by mundusnine** [comment]
Hi,

Basically, if I have a wasm compiled with emscripten, will it share the filesystem with  wasmFs ?

Because right now compilling with wasienv is, well, less documented then emscripten and I am literally trying to compile a compiler to wasm and the compiler(haxe compiler) uses other c libs and its unclear how to add those with wasienv compared to emscripten.

Good day and thank you,

**Comment by torch2424** [comment]
Hello!

So both should use WasmFs when used in the Wasm Terminal, or [WebAssembly.sh](https://webassembly.sh/).

And woah! That sounds like a really cool / fun project! 😄 Excited to see it!

No matter what tool you use to compile your Wasm modules, they should have access to their FileSystem if they have the correct WASI bindings, which in turn means they can use WasmFs. @syrusakbary please correct me if I am wrong 😄 

Let me know if that helps! Thanks!

**Comment by syrusakbary** [comment]
We have now added full docs into Wasmer-JS, which should make clearer how to use the SDK moving forward
