### ISSUE TITLE
How to send stdin after program has been started?

### ISSUE THREAD

**Issue by richardanaya** [wasmerio/wasmer-js#304]
I'm trying to make a terminal app that runs in browser with wasmer-js, i'm trying to look at how the wasm_bindgen apis can be used to write to a terminal after it's been started (not the initial stdin).

**Comment by AlistairKeiller** [comment]
I would also like to know how to send stdin after the program has started.

**Comment by corwin-of-amber** [comment]
This feature is unfortunately not supported by Wasmer-JS, and for a rather subtle but in-hindsight obvious reason: code running in a JS/WASM runtime is single-threaded, but C programs like bash etc. use a "blocking" API to access stdin. There is no async/await in WASM and there is no mechanism to suspend the currently executing stack frame. Even if the WASM program is running in a Web Worker, it will not be able to handle messages (sent e.g. by `postMessage` from the UI thread) *until the program has exited*.

That said, there is a roundabout way to achieve a semblance of a blocking stream using JS's SharedArrayBuffer and Atomics. I have successfully used this approach in [wasi-kernel](https://github.com/corwin-of-amber/wasi-kernel/blob/master/src/kernel/streams.ts); the trouble with wasi-kernel is that it is based on the older TypeScript-based version of Wasmer-JS. I am working on doing the same in Rust but have not gotten very far, mostly due to my inexperience in Rust. If you're interested, you can look at [this branch](https://github.com/corwin-of-amber/wasmer-js/tree/stdio-copipe) in my fork of Wasmer-JS.

**Comment by Michael-F-Bryan** [comment]
It's now possible to do this because we've re-implemented the package from the ground up. WebAssembly programs now run on Web Workers in the background and a user can choose to either provide a statically-known `stdin` when spawning a process or leave `stdin` as `undefined` and access the `WritableStream` attached to an instance's `stdin` field.

Here is an example from one of our tests:

https://github.com/wasmerio/wasmer-js/blob/d6ed31b7463ba1350022571438262f6a58061558/tests/integration.test.ts#L45-L70
