### ISSUE TITLE
Clarification on persistent file system access in browsers

### ISSUE THREAD

**Issue by vincent-herlemont** [wasmerio/wasmer-js#393]
When you talk about ['FileSystem access'](https://docs.wasmer.io/javascript-sdk/how-to/use-filesystem) in browsers, does this mean that the data is persistent? Through OPFS or another storage offered by browsers?

---

Context https://github.com/vincent-herlemont/native_db/issues/65

**Comment by Michael-F-Bryan** [comment]
When you use the `new Directory()` constructor, it will create a temporary in-memory filesystem that is backed by a [`virtual_fs::mem_fs::FileSystem`](https://docs.rs/virtual-fs/0.8.0/virtual_fs/mem_fs/struct.FileSystem.html). 

In #337, I'm adding a static `Directory.fromBrowser()` function which will create a `Directory` backed by the browser's [FileSystem API](https://developer.mozilla.org/en-US/docs/Web/API/File_System_API). That means you'd be able to mount a directory backed by OPFS or the `FileSystemDirectoryHandle` you get from [`window.showDirectoryPicker()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/showDirectoryPicker).

That PR hasn't been merged yet, but that's mainly because we chose to implement the easier in-memory version first and add support for the FileSystem API after making `@wasmer/sdk` public.

**Comment by MentalGear** [comment]
Amazing work! Any indication when persistent OPFS will be available? This would all such high-demand applications like vector search in the browser by the very popular usearch library.
